[package]
name = "azul-desktop"
version = "0.0.5"
authors = ["Felix Schütt <felix.schuett@maps4print.com>", "The winit contributors"]
license = "MPL-2.0"
description = "Desktop rendering API for azul"
homepage = "https://azul.rs/"
keywords = ["gui", "user-interface", "svg", "graphics", "css" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2021"
autoexamples = false
build = "build.rs"

[dependencies]
azul-css                = { path = "../css", version = "0.0.1",  default-features = false, features = ["parser"]}
azul-core               = { path = "../azul-core", version = "0.0.2",  default-features = false }
azul-layout             = { path = "../azul-layout", version = "0.0.4",  default-features = false, features = ["text_layout"] }
tinyfiledialogs         = { version = "3.9.1",  default-features = false }
clipboard2              = { version = "0.1.1",  default-features = false }
raw-window-handle       = { version = "0.5.0", default-features = false }
log                     = { version = "0.4.17",  default-features = false, optional = true }
fern                    = { version = "0.6.1",  default-features = false, optional = true }
backtrace               = { version = "0.3.66" }
rust-fontconfig         = { version = "0.1.13", default-features = false, features = ["std", "parsing"] }
strfmt                  = { version = "0.1.6", default-features = false }
libm                    = { version = "0.2.2", default-features = false }
gl-context-loader       = { version ="0.1.8", default-features = false }
webrender               = { version = "0.62.2", package = "azul-webrender", default-features = false, features = ["freetype-lib"] }
once_cell = "1.17.1"
dispatch2 = "0.2.0"
bitflags = "2.8.0"
block2 = "0.6.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", default-features = false, features = ["windowsx", "libloaderapi", "errhandlingapi", "winuser", "uxtheme", "dwmapi", "wingdi", "commdlg"] }

[target.'cfg(target_os = "macos")'.dependencies]
cgl = "0.3.2"
dispatch2 = { version = "0.2.0", default-features = false, features = [
    "std",
    "objc2",
] }
objc2 = "0.6.0"
objc2-core-foundation = { version = "0.3.0", default-features = true, features = [
    "std",
    "CFBase",
    "CFString",
    "CFBundle",
] }
objc2-foundation = { version = "0.3.0", default-features = true, features = [
    "std",
    "NSArray",
    "NSThread",
] }
objc2-app-kit = { version = "0.3.0", default-features = true, features = [
    "std",
    "objc2-core-foundation",
    "NSApplication",
    "NSResponder",
    "NSView",
    "NSWindow",
    "NSOpenGL",
    "NSOpenGLView",
] }

[features]
default = ["std", "logging", "css_parser", "font_loading", "text_layout", "svg", "xml", "image_loading", "gif", "jpeg", "png", "tiff", "bmp", "use_fern_logger"]
std = ["azul-core/std"]
use_pyo3_logger = []
use_fern_logger = ["fern"]
logging = ["log"]
css_parser = ["azul-core/css_parser", "azul-css-parser"]
font_loading = ["azulc/font_loading"]
text_layout = ["azulc/text_layout"]
svg = ["azulc/svg", "xml"]
xml = ["azulc/xml"]
image_loading = ["azulc/image_loading", "std"]
gif = ["image_loading", "azulc/gif"]
jpeg = ["image_loading", "azulc/jpeg"]
png = ["image_loading", "azulc/png"]
tiff = ["image_loading", "azulc/tiff"]
bmp = ["image_loading", "azulc/bmp"]
ico = ["image_loading", "azulc/ico"]
tga = ["image_loading", "azulc/tga"]
hdr = ["image_loading", "azulc/hdr"]
webp = ["image_loading", "azulc/webp"]
pnm = ["image_loading", "azulc/pnm"]
