[package]
name = "azul-examples"
version = "0.0.1"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
license = "MIT"
description = '''
    Azul GUI is a free, functional, immediate-mode GUI framework
    for rapid development of desktop applications written in Rust,
    supported by the Mozilla WebRender rendering engine
'''
homepage = "https://azul.rs/"
keywords = ["gui", "GUI", "user-interface", "svg", "graphics" ]
categories = ["gui"]
repository = "https://github.com/maps4print/azul"
edition = "2021"
publish = false

[[example]]
name = "test"
path = "test.rs"

[[example]]
name = "async"
path = "async.rs"

[[example]]
name = "hello-world"
path = "hello-world.rs"

[[example]]
name = "fontdebug"
path = "fontdebug.rs"

[[example]]
name = "widgets"
path = "widgets.rs"

[[example]]
name = "opengl"
path = "opengl.rs"
required-features = ["serde_support"]

[[example]]
name = "calculator"
path = "calculator.rs"

[[example]]
name = "nodegraph"
path = "nodegraph.rs"

[[example]]
name = "spreadsheet"
path = "spreadsheet.rs"

[[example]]
name = "svg"
path = "svg.rs"

[[example]]
name = "xml"
path = "xml.rs"

# [[example]]
# name = "table"
# path = "table.rs"

# [[example]]
# name = "udp-chat"
# path = "udp-chat.rs"

[dependencies]
azul = { path = "../../api/rust" }
serde = { version = "1", optional = true }
serde_derive = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
# libc_alloc = { version = "1.0.2", default-features = false }

[features]
default = []
serde_support = ["azul/serde", "serde", "serde_derive", "serde_json"]