[package]
name = "azul-ios"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
azul = { path = "../../../api/rust" }

[package.metadata.ios]
build_targets = ["aarch64-apple-ios", "aarch64-apple-ios-sim", "x86_64-apple-ios"]
dependencies = ["OpenGLES.framework", "GLKit.framework"]
deployment_target = "13.0"
bundle_id_prefix = "rs.azul.example"
code_sign_identity = "Apple Developer"
development_team = "XXXXXX"
