name: Reftest Runner

on:
  workflow_dispatch:
    inputs:
      testSubset:
        description: 'Specific test subset to run (leave empty for all tests)'
        required: false
        default: ''

jobs:
  run-reftests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk libfontconfig1-dev

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Check Chrome Installation
        run: google-chrome --version

      - name: Build Reftest Tool
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --package azul-reftest

      - name: Run Reftests
        run: |
          TEST_SUBSET="${{ github.event.inputs.testSubset }}"
          if [ -z "$TEST_SUBSET" ]; then
            ./target/release/azul-reftest
          else
            ./target/release/azul-reftest --subset "$TEST_SUBSET"
          fi

      - name: Package Test Results
        run: |
          cd reftest_output
          zip -r ../reftest-results.zip *

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: reftest-results
          path: reftest-results.zip
          if-no-files-found: error